fhsu-csci441-team-a/myTrafficWizard

.env, .gitignore, slack_bot.py
Slack bot currently works locally when sending a private message to user inside My Traffic Wizard workspace on Slack.
=> Slack Bot Working Locally to Send Private Message

slack_bot.js, static/css/style.css
Changed layout to include an option for larger screens that ensures the web page stays at one page height without scrolling.
=> Changed Layout for Largest Screens

services/BaseFetchRetry.js
The is an initial commit of a base class that will be used for retries on the web API requests - model classes will extend it without having to repeat the retry logic.
=> Add basefetchretry file

models/TravelTimeModel.js
This file exports a class that takes a route and calculates the applicable travel times.
=> add TravelTimeModel file

package.json
Doc for package: https://node-postgres.com/
=> add pg dependency to package.json

app.js, static/js/slack_bot.js
Updated the Routes to the individual route files to be sub-directories.
=> Updated Routes to Include Sub-Directories

controllers/homeController.js, controllers/notificationController.js, controllers/slackBotController.js
Created NotificationController class, added formSubmission functionality to HomeController, and updated SlackBotController to accept parameters internally in addition to via HTTP request.
=> Created NotificationController Class & Updated HomeController and SlackBotController

config/databaseConnection.js, models/scheduledTripsModel.js
- Add databaseConnection file
- Add scheduledTripsModel file
=> Feature database operations

controllers/homeController.js, models/addressModel.js, routes/homeRoutes.js, static/css/style.css, static/js/userInterface.js, views/index.html
Added Form submission handling, added route for /submit to use the homeController's formSubmission method, and improved the CSS of the index page.
=> Added Form Submission Handling, Route, and Improved CSS of Index

controllers/gmailController.js, controllers/homeController.js, controllers/notificationController.js, controllers/slackBotController.js, models/slackBotModel.js, tests/testNotificationController.js
The NotificationController is now working to send a message via email (through Gmail) and slack. The testNotificationController.js file imitates the scheduleController by creating a NotificationController object, querying the database for a trip, then passing that to the NotificationController object.
=> NotificationController Now Working with Sample Message

controllers/gmail.js, models/messageModel.js
Text and HTML message updated to use input.
gmail.js modified to test new MessageModel and delivery methods.
=> Modified messageModel.js to handle changed input variable types.

app.js, controllers/homeController.js, controllers/notificationController.js, routes/gmailRoutes.js, routes/homeRoutes.js, static/css/style.css, static/js/userInterface.js, tests/testNotificationController.js, tests/views/send_messages.html, views/index.html
Created the front-end user interface and updated the testing function to include a passed tripId parameter. This allows the tester to pull a specific trip from the database. This can then be used to test the NotificationController class the the message processing and sending. Also added a form submission message that displays a success message to the user with the tripId.
=> Created Front-End Interface and Updated Testing for NotificationController Class and Sending Messages and Added Form Submission Message

README.md
I added a lot more information to our readme to improve our documentation.
=> Added to Our Readme

app.js, controllers/homeController.js, static/js/userInterface.js, tests/controllers/testNotificationController.js
Added parameter passed to constructor of ScheduledTripsModel and adjusted routes for new folder structure.
=> Added Parameter Passed to ScheduledTripsModel

app.js, tests/controllers/testNotificationController.js, tests/views/send_messages.html
Added feedback to send_messages.html page so that the page will display a message indicating success/failure of message sending.
=> Added Feedback To send_messages.html Page

static/js/userInterface.js, views/index.html
Changed email address to be required field. Commented out the checkbox handler for email in userInterface to prevent error.
=> Changed Email Address to Be Required Field

README.md
Added note about Render App sleeping and potentially needing time to load.
=> Added Note About Render App Sleeping

controllers/gmailController.js, tests/controllers/gmailController.test.js, tests/controllers/slackBotController.test.js
- Add unit tests for slackBotController and gmailController
=> Create unit tests

README.md
Updated the ReadMe file to include the instructions for users to sign up for the Slack workspace and Discord server. Also included instructions on how to find their User ID.
=> Updated ReadMe to Include Slack/Discord Instructions

controllers/notificationController.js, tests/testNotificationController.js
Updates for SMS message implementation.
=> Updating for SMS Message Implementation

controllers/notificationController.js
Now using 1 GmailController object for both SMS and email.
=> Switched to Using 1 GmailController Object

controllers/notificationController.js, tests/testNotificationController.js
Added comments explaining purpose of files.
=> Added File Comments

controllers/discordBotController.js, controllers/notificationController.js, models/discordBotModel.js, package-lock.json, package.json, routes/discordRoutes.js, static/js/discord_bot.js, views/discord_bot.html
Changes to Discord files and NotificationController are now allowing the Dicord Bot to send direct messages to users!
=> Discord Bot Now Working!!!

controllers/discordBotController.js, controllers/notificationController.js, models/discordBotModel.js
Figured out how to properly and thoroughly and utterly destroy the persistent, hard-to-kill Discord connection.
=> Now Properly Destroying the Discord Connection

controllers/discordBotController.js, controllers/notificationController.js, models/discordBotModel.js
Updated the methods in DiscordBotModel so that the destroy() and login() methods could be called from DiscordBotController. This seems to change the timing enough to prevent hanging, while calling these within the class itself causes hanging.
=> Updated DiscordBotModel Methods and Calls

controllers/homeController.js, models/scheduledTripsModel.js, static/js/userInterface.js
- Moved conversion of departure date to ISO string to user interface to help resolve issue of database not storing departure dates in UTC.
=> Fix timezone
